config/routes.rb
Storm::Application.routes.draw do
  resources :users

  resources :locations

  root 'locations#new'
  get '/default' => 'main#index', as: :default

  post '/get_forecast/(.:format)' => 'main#create'
  get '/get_forecast' => 'main#get_forecast', as: :get_forecast

  

end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :address, :latitude, :longitude
	geocoded_by :address # can also be an IP address
  	reverse_geocoded_by :latitude, :longitude do |address,results|
  		if geo = results.first
    		address.city = geo.city
    		address.state = geo.state_code
    		address.street = geo.address
    		address.country = geo.country
  		end
	end
	after_validation :geocode, :reverse_geocode # auto-fetch address	
  	validates :address, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/weather.rb
class Weather < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require "sprockets/railtie"
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	def get_weather_image(icon)
		icons = {"clear-day" => "CLEAR_DAY", "clear-night" => "CLEAR_NIGHT", "partly-cloudy-day" => "PARTLY_CLOUDY_DAY", "partly-cloudy-night" => "PARTLY_CLOUDY_NIGHT", "cloudy" => "CLOUDY", "rain" => "RAIN", "sleet" => "SLEET", "snow" => "SNOW", "wind" => "WIND", "fog" => "FOG"}
		return icons[icon]
	end

	def get_temperature_info(temp)
    temp = temp.round
    return temp
  end

  def get_summary_description(summary)
    #Placeholder method. Fill In.
    #Check which summary it is and return correct description
    return summary
  end

end

app/controllers/locations_controller.rb
require 'weather_forecast'
require 'time'

class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  def get_summary_description(summary)
    #Placeholder method. Fill In.
    #Check which summary it is and return correct description
    return summary
  end

  def convert_time(time)
    time = Time.at(time).to_date.strftime("%A")
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @weather_json = Weather_Forecast.get_forecast(@location.latitude, @location.longitude)

    #Currently
    @time = Time.at(@weather_json["currently"]["time"])
    @summary = get_summary_description(@weather_json["currently"]["summary"])
    @icon = get_weather_image(@weather_json["currently"]["icon"])
    @temp = get_temperature_info(@weather_json["currently"]["temperature"])
    @feelsLike = get_temperature_info(@weather_json["currently"]["apparentTemperature"])
    @precip = @weather_json["currently"]["precipProbability"]
    @intensity = (100 * @weather_json["currently"]["precipIntensity"]).round

    #Daily
    index = 0
    @daily_summary = [], @daily_icon = [], @daily_lowtemp =  [], @daily_hightemp = [], @daily_time = [], @daily_precip = [], @daily_cloud = []
      #5 times to include today and next 4 days
      7.times do
        @daily_summary[index]= get_summary_description(@weather_json["daily"]["data"][index]["summary"])
        @daily_icon[index]=  get_weather_image(@weather_json["daily"]["data"][index]["icon"])
        @daily_lowtemp[index]= get_temperature_info(@weather_json["daily"]["data"][index]["temperatureMin"])
        @daily_hightemp[index]=  get_temperature_info(@weather_json["daily"]["data"][index]["temperatureMax"])
        @daily_time[index]=  convert_time(@weather_json["daily"]["data"][index]["time"])
        @daily_precip[index]= (100 * @weather_json["daily"]["data"][index]["precipProbability"]).round
        @daily_cloud[index] = (100 * @weather_json["daily"]["data"][index]["cloudCover"]).round
        index = index + 1
      end

    #Hourly
    @hourly_summary = @weather_json["hourly"]["summary"]

    #Minutely
    @minutely_summary = @weather_json["minutely"]["summary"]

    
    #Alerts
    @alert_index = @weather_json["alerts"]
    if @alert_index
      @alert_title = @weather_json["alerts"][0]["title"]
      @alert_url = @weather_json["alerts"][0]["uri"]
      @alert_time = @weather_json["alerts"][0]["time"]
      @alert_description = @weather_json["alerts"][0]["description"][0..116]
    end
 
  end

  # GET /locations/new
  def new
    @location = Location.new

  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def navMainAktiv(actionName)
    if params[:controller] == actionName    
    "active"
    end
	end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Where's the Storm?</title>
  <link rel="shortcut icon" href="http://www.popupstorms.com/wp-content/uploads/2011/03/StormIcon.jpg"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- iPad (Retina) -->
<link rel="apple-touch-icon"
      sizes="144x144"
      href="http://www.popupstorms.com/wp-content/uploads/2011/03/StormIcon.jpg">
<!-- Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Coda:bold" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Kreon" rel="stylesheet" type="text/css">
<!-- End Fonts-->
  


  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>

<body>
<!--Navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Where's the Storm?</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="#">Blog</a></li>
    </ul>

<% if @location %>
    <%= form_for(@location, :html => {:class=> "navbar-form navbar-right "}) do |f| %>
      <div class="field">
        <div class="form-group"><%= f.text_field :address, :class => 'form-control', :placeholder => 'search for storms' %>
        </div><%= f.submit "Storm?", class: "btn btn-primary" %>
      </div>
    <% end %>
<% end %>

  </div><!-- /.navbar-collapse -->
</nav>
<!-- End Navbar -->


<!--Page Content -->
      <div class="container">
        <%= yield %>
      </div>
<!-- End Page Content -->






   
<!--Footer-->
<nav class="navbar navbar-inverse navbar-default navbar-fixed-bottom" role="navigation">
  <p class="navbar-text pull-left" id="footer">Created by 
    <a href="https://twitter.com/jim_challenger" class="navbar-link">Jim Challenger</a> &
    <a href="https://twitter.com/sirjustinwhite" class="navbar-link">Justin White</a>
  </p>
  <p class="navbar-text pull-right" id="footer">
    <a href="http://forecast.io" class="navbar-link" target="_blank">Powered by Forecast.io</a>
  </p>
</nav>
<!--End Footer--> 


</body>
</html>

app/views/locations/_form.html.erb
<div class="row"><div class="alert alert-dismissable alert-success col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Welcome!</strong> Where's the Storm is still in development right now. Feel free to poke around, and let us know what you think <a href="mailto:hello@wheresthestorm.com" class="alert-link">here!</a>
</div></div>


<div class="row"><%= form_for(@location, :html => {:class=> "form-horizontal"}) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
    <h1 id="logo">Where's the Storm?</h1>
    <p id="logo" class="lead"><strong>We love storms...</strong></p>
    <div class="row"><%= f.text_field :address, :class => 'form-control', :placeholder => 'search for storms '  %></div>
    <div class="row"><%= f.submit "Storm?", class: "btn btn-primary col-lg-12 col-md-12 col-sm-12 col-xs-12", id: "search-button" %></div>
  </div>


</div>
<% end %> 

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.street %></td>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.country %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<body id="home">
<div class="container">
	<%= render 'form' %>
</div>
</body>

app/views/locations/show.html.erb
<body id="results"><!-- Google Maps Background-->
<div id="map-container"><%= image_tag "http://maps.google.com/maps/api/staticmap?size=650x650&sensor=false&zoom=13&center=#{@location.latitude}%2C#{@location.longitude}&visual_refresh=true&scale=2&key=AIzaSyCAaruC-8uY0mbl_eXQRT0Co4ou_EKr9cI", :id =>"map", :class => "img-rounded img-responsive" %></div> 
<!-- END Google Maps Background-->

<!-- Severe Weather Alerts  || needs if statement to hide if no alert exists -->
<% if @weather_json["alerts"] %>
<div class="alert alert-dismissable alert-danger col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Warning! <%= @alert_title%>.</strong><p><small><%=@alert_description %>...</small></p><a href="<%= @alert_url %>" class="alert-link">More info here!</a>
</div>
<% end %>

 <!-- END Severe Weather Alerts -->


<!-- New Jumbotron -->

<div class="row">
    <div class="jumbotron col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <div class="container">
        <h1>Today   <small><%= @location.city %>, <%= @location.state %> </small></h1>
         <p id="temp"> <strong><%=@daily_hightemp[0]%>°</strong> <small><%=@daily_lowtemp[0]%>°</small></p> 
        <div><p id="today-weather" class="pull-right"><strong><%=@daily_time[0]%><br /><strong><canvas id="icon0" width="123" height="123"></canvas></p></p></div>
          <p><%=@daily_summary[0] %></p>
          <p><%=@daily_precip[0]%>% chance of rain</p>
          <p><small><%=@daily_cloud[0]%>% cloud coverage</small></p>
      </div>
    </div>

    <div class="jumbotron col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
      <div class="container">
        <h2>Currently   <small><%=@summary %></small></h2>
        <div><p class="pull-right"><canvas id="icon1" width="123" height="123"></canvas></p></div>
          <p><%=@minutely_summary %></p>
          <p><strong>Current Temp: </strong><%=@temp%>°</p>
          <p><strong>Feels Like: </strong><%= @feelsLike%>°</p>
          <p>Coming Up: <%=@hourly_summary %></p>
      </div>
    </div>
</div>
<!-- END New Jumbotron -->

<!-- Forecast -->
<div class="row">
<% index = 1 %>
<% 6.times do %>
  <div class="col-lg-2 col-md-4 col-sm-4 col-xs-6 forecast container-forecast well">
    <div class="row">
      <strong><p class="lead"><strong><%=@daily_time[index]%></strong></p></strong>
    </div>
    <div class="row">
      <p id="temp"> <strong><%=@daily_hightemp[index]%>°</strong> <small><%=@daily_lowtemp[index]%>°</small></p> 
    </div>
    <div class="row">
       <p><%=@daily_summary[index]%></p>
    </div>
    <div class="row">
      <% case index+1 %>
      <% when 1 %>
        <canvas id="icon1" width="100" height="100"></canvas>
      <% when 2 %>
        <canvas id="icon2" width="100" height="100"></canvas>
      <% when 3 %>
        <canvas id="icon3" width="100" height="100"></canvas>
      <% when 4 %>
        <canvas id="icon4" width="100" height="100"></canvas>
      <% when 5 %>
        <canvas id="icon5" width="100" height="100"></canvas>
      <% when 6 %>
        <canvas id="icon6" width="100" height="100"></canvas>
      <% when 7 %>
        <canvas id="icon7" width="100" height="100"></canvas>
      <% end %>
    </div>
  </div>
<% index = index + 1 %>
<% end %>
</div>
<!-- END Forecast -->

                <!-- Old Code Keep for weather-inline format     
                        <ul id="weather-inline">
                          <li class="weather-item"><canvas id="icon1" width="164" height="164"></canvas></li>
                          <li class="weather-item"><dl class="dl-horizontal">
                            <dt></dt><dd><h3>Right Now</h3></dd>
                            <dt></dt><dd><h1 id="temp center"><%=@temp%>°</h1></dd>
                            <dt>Condition:</dt> <dd><%=@summary%></dd>
                            <dt>Precipitation:</dt> <dd> <%=@precip%>% <small>chance</small></dd>
                            <dt>Precip. Intensity:</dt> <dd> <%=@intensity%></dd>
                            <dt>Wind Speed:</dt> <dd> <%=@wind.to_i%> mph</dd>
                          </dl></li>
                        </ul>
                until phased into new jumbotron-->

<%= javascript_tag do %>
  var skycons = new Skycons({"color": "#89CFF0"});
  skycons.add("icon1", Skycons.<%=@icon%>);
  skycons.add("icon0", Skycons.<%=@daily_icon[0]%>);
  skycons.add("icon2", Skycons.<%=@daily_icon[1]%>);
  skycons.add("icon3", Skycons.<%=@daily_icon[2]%>);
  skycons.add("icon4", Skycons.<%=@daily_icon[3]%>);
  skycons.add("icon5", Skycons.<%=@daily_icon[4]%>);
  skycons.add("icon6", Skycons.<%=@daily_icon[5]%>);
  skycons.add("icon7", Skycons.<%=@daily_icon[6]%>);
  skycons.play();
<% end %>
</body>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>